spring:
  jpa:
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://192.168.1.250:3306/flight_db_qa
    driver-class-name: org.mariadb.jdbc.Driver
    username: ritaQA
    password: allus_softQA
    hikari:
      idle-timeout: 10000
      pool-name: api-pool
      maximum-pool-size: 100

logging:
  level:
    root: info
    org.springframework: info
