server:
  port: 8090

spring:
  profiles:
    active: dev
  application:
    name: flight-ripper
  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  swagger-ui:
    enabled: true
